JDP200802-2
hacker-msl/project-jdp-2008-02 pull request #1
Opened 2020-08-21 14:13 UTC by hakhis

Udało się odpalić aplikację, więc tą część komentarza można zignorować.
Zgodnie z zadaniem zwraca na razie tylko dane testowe

2020-08-24 19:39 UTC, hacker-msl requested changes

2020-08-24 19:39 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public void createGroup(GroupDTO groupDTO){
w PR https://github.com/hacker-msl/project-jdp-2008-02/pull/7/files kolega z zespołu zwraca obiekt na metodzie tworzącej. Mamy lekką rozbieżność, naprawimy to jakoś ? Może dogadacie się jak to rozwiązać ?

2020-08-24 19:39 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/GroupNotFoundException.java
> +public class GroupNotFoundException extends Exception{
ja zdecydowanie odradzam  używanie wyjątków kontrolowanych w nowoczesnej Javie. Zmień na RuntimeException. Poza tym może warto stworzyć pakiet exceptions ?

2020-08-24 19:39 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/GroupDTO.java
> +public class GroupDTO {
a gdzie lombok? w pozostałych PR wszędzie jest lombok i tak ustaliliśmy podczas rozmowy

2020-08-24 19:39 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/GroupController.java
>  package com.kodilla.ecommercee;
może stworzymy pakiet na kontrolery ? 
np. com.kodilla.ecommercee.controller?

2020-08-26 20:32 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/GroupController.java
> +    public void createGroup(GroupDTO groupDTO){
Teraz zwracam GroupDTO

2020-08-26 20:35 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/GroupNotFoundException.java
> +public class GroupNotFoundException extends Exception{
Na chwilę obecną wywaliłem to z projektu. Będzie jeszcze pora na omówienie wyjątków w projekcie ;)

2020-08-26 20:36 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/domain/GroupDTO.java
> +public class GroupDTO {
Lombok dodany. Przy poprzednim PR skupiłem się na controllerze i przeoczyłem.

2020-08-26 20:37 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/GroupController.java
>  package com.kodilla.ecommercee;
Dodałem również pakiet

2020-08-27 05:35 UTC, hacker-msl approved these changes

2020-08-27 05:36 UTC, hacker-msl approved these changes

2020-08-27 05:36 UTC, merged