Jdp200802 4
hacker-msl/project-jdp-2008-02 pull request #11
Opened 2020-08-29 18:21 UTC by krzysztof-galazka

2020-08-31 11:29 UTC, F1iper approved these changes

2020-09-01 09:49 UTC, hacker-msl commented
@F1iper skoro jest OK to miałeś mnie przypisać jako 2 osobę do review...

2020-09-01 09:53 UTC, hacker-msl requested changes

2020-09-01 09:53 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    @DeleteMapping
@PathVariable powinien iść z parametrem w adnotacji mappingu,
np: @DeleteMapping("/{id}")
https://www.journaldev.com/3358/spring-requestmapping-requestparam-pathvariable-example#spring-pathvariable

2020-09-03 20:11 UTC, hacker-msl approved these changes

2020-09-03 20:11 UTC, merged