Jdp200802 14
hacker-msl/project-jdp-2008-02 pull request #12
Opened 2020-08-30 13:30 UTC by F1iper

2020-08-30 18:45 UTC, krzysztof-galazka approved these changes

2020-09-01 09:36 UTC, hacker-msl commented
hej, ja to mogę sprawdzać? czemu @krzysztof-galazka  nie przypisał do mnie PRki ? mamy konflikty, rozwiążcie je, proszę.

2020-09-01 09:44 UTC, hacker-msl requested changes
1) build nie przechodzi: 
ateo@linux-to0r:~/eclipse-workspace/kodilla/project-jdp-2008-02> ./gradlew build        

> Task :test

com.kodilla.ecommercee.EcommerceeApplicationTests > contextLoads FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException

com.kodilla.ecommercee.SpringBootJPAIntegrationTest > givenGenericEntityRepository_whenSaveAndRetreiveEntity_thenOK FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException

2 tests completed, 2 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///
2) mamy konflikty do rozwiązania

2020-09-01 09:44 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +public class OrderController {
po co nam pusty kontroler? zrób merge z mastera do tego brancha, może zniknie...

2020-09-01 09:44 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +public class UserController {
po co nam pusty kontroler? zrób merge z mastera do tego brancha, może zniknie...

2020-09-01 09:44 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Cart cart;
czy produkt powinien mieć relację do Cart? jeśli tak, to czy taką? jeden produkt powinien móc się znaleźć w wielu Cart, więc dlatego @ManyToOne?

2020-09-01 09:44 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Order order;
czy produkt powinien mieć relację do Order? jeśli tak, to czy taką? jeden produkt powinien móc się znaleźć w wielu Order, więc dlatego @ManyToOne?

2020-09-02 08:25 UTC, hacker-msl commented
@krzysztof-galazka sprawdź proszę ponownie ten PR. Sprwadź też czy się buduje i odpala. Dopiero jak wszystko jest OK, daj approve.

2020-09-02 20:27 UTC, hacker-msl requested changes

2020-09-02 20:27 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +    private Cart cart;
w mojej ocenie Product powinien być powiązany relacją N:N , czyli wiele do wielu... dlatego, że w jednym koszyku może być wiele produktów, a jeden produkt może znajdować się w wielu koszykach.

2020-09-02 23:00 UTC, krzysztof-galazka commented
wg. mnie wszystko jest ok

2020-09-05 12:41 UTC, AdamWojcicki1991 commented
![image](https://user-images.githubusercontent.com/60105724/92305259-e763fd00-ef85-11ea-90b1-80fd0bc6445b.png)
Przypominam o relacjach ustalonych na spotkaniu :)

2020-09-06 15:16 UTC, hacker-msl commented
@F1iper nie wiem co mam z tym zrobić bo pojawił się PR #17  i nie wiem co i jak z tymi PR - jak Wy to widzicie. Opiszcie proces merge'owania jaki za tym idzie i dlaczego jest osobny PR zamiast zmian do wiszących ?

2020-09-10 05:06 UTC, hacker-msl commented
mamy konflikty z: 
src/test/java/com/kodilla/ecommercee/SpringBootJPAIntegrationTest.java

2020-09-11 19:48 UTC, hacker-msl commented
@krzysztof-galazka sprawdzisz ten PR ?

2020-09-12 19:53 UTC, hacker-msl commented
konflikty:
src/main/java/com/kodilla/ecommercee/controller/UserController.java
src/main/java/com/kodilla/ecommercee/domain/Cart.java
src/main/java/com/kodilla/ecommercee/domain/Order.java
src/main/java/com/kodilla/ecommercee/domain/User.java

ktoś sprawdzi ten PR ?!

2020-09-13 08:41 UTC, F1iper reviewed
Fix'd

2020-09-13 09:05 UTC, krzysztof-galazka commented
były konflikty - poprawiłem, wg. mnie jest ok

2020-09-13 09:05 UTC, krzysztof-galazka approved these changes

2020-09-13 16:09 UTC, F1iper commented
> 
> 
> były konflikty - poprawiłem, wg. mnie jest ok

👍

2020-09-14 09:27 UTC, hacker-msl approved these changes

2020-09-14 09:27 UTC, merged