Jdp200802 12
hacker-msl/project-jdp-2008-02 pull request #14
Opened 2020-08-30 20:21 UTC by krzysztof-galazka

2020-08-31 05:47 UTC, AdamWojcicki1991 requested changes
To zadanie dotyczy tylko stworzenia encji product i ewentualnych pustych encji jeśli występują relację i klas jeśli dodajesz jakieś nowe których nie ma jeszcze w projekcie a używasz je jako typy pól encj. Reszta powinna stąd wylecieć.

2020-09-01 09:48 UTC, hacker-msl commented
@krzysztof-galazka robił chyba na starym branchu master - dlatego pojawiają się zmiany z innych branchy, które już zostały zmerge'owane. Zrób @krzysztof-galazka merge z mastera do tego brancha i wypchnij. I tak to musisz zrobić bo są konflikty.

Conflicting files
src/main/java/com/kodilla/ecommercee/domain/Cart.java
src/main/java/com/kodilla/ecommercee/domain/Product.java

2020-09-02 08:23 UTC, hacker-msl requested changes
hej, cały czas widzę jakieś puste kontrolery tutaj, 
są też konflikty:
src/main/java/com/kodilla/ecommercee/controller/UserController.java

2020-09-04 08:18 UTC, AdamWojcicki1991 commented
Dalej mamy konflikty więc czekamy.

2020-09-04 17:43 UTC, hacker-msl commented
Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.kodilla.ecommercee.domain.Product.order in com.kodilla.ecommercee.domain.Order.products


Caused by: org.hibernate.AnnotationException: mappedBy reference an unknown target entity property: com.kodilla.ecommercee.domain.Product.order in com.kodilla.ecommercee.domain.Order.products
	at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:785)

2020-09-05 12:41 UTC, AdamWojcicki1991 commented
![image](https://user-images.githubusercontent.com/60105724/92305242-c4d1e400-ef85-11ea-8a7f-1c6fcd3b73f9.png)
Popraw relacje zgodnie z UML omówionym na spotkaniu.

2020-09-06 15:15 UTC, hacker-msl commented
hej @krzysztof-galazka mamy tu konflikty, rozwiążesz? 
src/main/java/com/kodilla/ecommercee/controller/OrderController.java
src/main/java/com/kodilla/ecommercee/controller/UserController.java

2020-09-08 06:36 UTC, hacker-msl commented
hej @AdamWojcicki1991 , zerkniesz dzisiaj ? :-)

2020-09-08 19:20 UTC, hacker-msl commented
o, wywaliło konflikty w:
src/test/java/com/kodilla/ecommercee/SpringBootJPAIntegrationTest.java

2020-09-08 20:11 UTC, krzysztof-galazka commented
@hacker-msl - poprawione

2020-09-09 20:51 UTC, hakhis commented
Przy budowaniu projektu nie przechodzą testy GroupServiceDbTestSuite, które przechodzą bez problemu na masterze.
`> Task :test

com.kodilla.ecommercee.EcommerceeApplicationTests > contextLoads() FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.AnnotationException

com.kodilla.ecommercee.service.GroupServiceDbTestSuite > shouldSaveGroup() FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.AnnotationException

com.kodilla.ecommercee.service.GroupServiceDbTestSuite > shouldGetGroupById() FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.AnnotationException

com.kodilla.ecommercee.service.GroupServiceDbTestSuite > shouldGetAllGroups() FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.hibernate.AnnotationException

4 tests completed, 4 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
`
Poza tym ta gałąź powoduje usuwanie UserDTO w gałęzi master

2020-09-09 20:58 UTC, hakhis requested changes
Pojawiają się problemy z UserDTO, prawdopodobnie spowodowane zmianą wielkości liter.
Poza tym nie wykonują się testy GroupServiceDbTestSuite, które na głównej gałęzi wykonują się bez problemu

2020-09-11 19:47 UTC, hacker-msl commented
@hakhis  sprawdzisz ten PR ?

2020-09-12 19:57 UTC, hacker-msl commented
hej @krzysztof-galazka , konflikty do poprawki:
src/main/java/com/kodilla/ecommercee/domain/Cart.java
src/main/java/com/kodilla/ecommercee/domain/Order.java
src/main/java/com/kodilla/ecommercee/domain/OrderStatus.java
src/test/java/com/kodilla/ecommercee/SpringBootJPAIntegrationTest.java
src/test/java/com/kodilla/ecommercee/service/GroupServiceDbTestSuite.java

2020-09-12 21:01 UTC, krzysztof-galazka commented
zrobione konflikty + merge z mastera

2020-09-13 05:56 UTC, AdamWojcicki1991 requested changes
Nie komentuj niepotrzebnego kodu tylko go po prostu usuń :P

2020-09-13 06:07 UTC, AdamWojcicki1991 approved these changes

2020-09-13 08:51 UTC, krzysztof-galazka commented
@AdamWojcicki1991 komentarze usunięte

2020-09-14 09:31 UTC, hacker-msl approved these changes

2020-09-14 09:32 UTC, hacker-msl commented
mamy konflikty, po rozwiązaniu możemy robić merge: 
Conflicting files
src/main/java/com/kodilla/ecommercee/domain/Cart.java
src/test/java/com/kodilla/ecommercee/SpringBootJPAIntegrationTest.java

2020-09-14 16:33 UTC, krzysztof-galazka commented
@hacker-msl - konflikty rozwiązane

2020-09-15 10:35 UTC, merged