Jdp200802 1
hacker-msl/project-jdp-2008-02 pull request #5
Opened 2020-08-21 17:54 UTC by AdamWojcicki1991

Prepare product controller skeletone v.1

2020-08-24 10:37 UTC, AdamWojcicki1991 commented
Oprócz taska do wykonania przepakietowałem również projekt i dołożyłem mappery i repo do obsługi bazy danych aby kontroller poprawnie działał. Zostawiłem domyślnie skonfigurowane encje (zgodnie z początkowym projekttem) z komentarzem //TODO

2020-08-24 16:57 UTC, hacker-msl requested changes
te zadanie miało dotyczyć tylko kontrolera w wersji minimum. Wszystko inne ma stąd wylecieć.

2020-08-26 16:18 UTC, AdamWojcicki1991 commented
Ok to zmieniłem to na bardziej podstawową wersję.

2020-08-26 16:28 UTC, hacker-msl requested changes

2020-08-26 16:28 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        System.out.println("Create product");
inni członkowie zespołu przy create zwracają Dto, tak mamy np tutaj: 
https://github.com/hacker-msl/project-jdp-2008-02/blob/8c48fff9efbbf51ea2eebf34d75fe655d23b2036/src/main/java/com/kodilla/ecommercee/controller/CartController.java#L17
zmień to tak, żeby to było zgodne.

2020-08-26 17:27 UTC, AdamWojcicki1991 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        System.out.println("Create product");
Oki

2020-08-27 05:32 UTC, hacker-msl approved these changes

2020-08-27 05:33 UTC, merged