Jdp200802 15
hacker-msl/project-jdp-2008-02 pull request #6
Opened 2020-08-22 15:14 UTC by AdamWojcicki1991

2020-08-24 19:40 UTC, hacker-msl commented
@AdamWojcicki1991  coś się tu dzieje ?

2020-08-26 16:50 UTC, AdamWojcicki1991 commented
Na razie za komentowałem relacje żeby projekt się budował bez potrzeby tworzenia dodatkowej encji, którą ktoś inny będzie robił.

2020-08-27 05:24 UTC, hacker-msl requested changes

2020-08-27 05:24 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +//    @OneToMany(
Jeśli ma być relacja do Order, to ją zrób. Zrób pustą klasę Order.

2020-08-27 05:24 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "CREATE_ACCOUNT_DATE")
adnotacja @Column nie jest potrzebna tak naprawdę...

2020-08-27 05:24 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "USER_STATUS")
adnotacja @Column nie jest potrzebna tak naprawdę...

2020-08-27 05:24 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "PASSWORD")
adnotacja @Column nie jest potrzebna tak naprawdę...

2020-08-27 05:24 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "LOGIN")
adnotacja @Column nie jest potrzebna tak naprawdę...

2020-08-27 05:24 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +@Table(name = "USERS")
name nie jest potrzebny tak długo jak nazwa generowana nie stanie się słowem kluczowym docelowego silnika bazy danych - np "Order" w MySQL.

2020-08-27 16:09 UTC, AdamWojcicki1991 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +@Table(name = "USERS")
Ok dzięki za tipa :)

2020-08-28 08:31 UTC, hacker-msl requested changes

2020-08-28 08:31 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @JoinColumn(name = "USER_ID")
Name w JoinColumn jest zbędny raczej

2020-08-28 17:51 UTC, hacker-msl requested changes
taki mam komunikat przy uruchamianiu: 

org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table order add constraint FKt7abetueht6dd1gs9jyl3o4t7 foreign key (user_id) references user (id)" via JDBC Statement


Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order (id bigint not null, user_id bigint, primary key (id)) engine=MyISAM' at line 1

2020-08-28 17:51 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/UserStatus.java
> +public enum UserStatus {
spoko, że używasz enum ale tego w kursie nie ma... najwyżej będziesz tłumaczył kolegom z zespołu ;)

2020-08-28 17:51 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
kolega używa CrudRepository, sugeruję jednak użycie JpaRepository
 
https://github.com/hacker-msl/project-jdp-2008-02/blob/95ec9dd9c31516cb8a227d0200a77c06b21b97a7/src/main/java/com/kodilla/ecommercee/repository/ProductGroupRepository.java#L9

2020-08-29 16:14 UTC, AdamWojcicki1991 commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Czekam na klepnięcie to wezmę sobie następną encje :)

2020-08-29 18:10 UTC, hacker-msl approved these changes

2020-08-29 18:11 UTC, merged