Jdp200802 3
hacker-msl/project-jdp-2008-02 pull request #7
Opened 2020-08-22 17:08 UTC by F1iper

2020-08-24 17:59 UTC, F1iper commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public void createEmptyCart(@PathVariable Long cartId) {
Cześć, nie wiem czy dobrze to zrobiłem ale 30 min po Twoim komentarzu poprosiłem o re-review (tak mi się zdaje), po wysłaniu tego niekompilującego się kodu, miałem problem jakie dane zwracać i czy tworzyć klasę, np. ProductDto (nie wiem czy nie skomplikuje to naszego projektu jeżeli każdy będzie tworzył takie puste klasy (?).
W tej chwili: 
Projekt się kompiluje.
**createEmptyCart** - po testach w postmanie - *wydaje mi się*, że działa, 
**getEmptyCart** - zwraca pustą ArrayListę,
**addProductToCart** - z tą metodą mam problem, nie wiem jaki powinien być typ zwracany, oraz czy parametry są ok,
**deleteProduct** - tutaj też mam problem ze zwracanym typem, wydaje mi się, że powinien to być boolean, a w parametrach cartId oraz productId ?
**createOrderFromCart** - metoda zwraca obiekt typu OrderDto.

2020-08-24 19:30 UTC, hacker-msl requested changes

2020-08-24 19:30 UTC, hacker-msl commented on build.gradle
> +    implementation('mysql:mysql-connector-java')
już powyżej mamy ten connector do mysql... w linii 32

2020-08-24 19:30 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +        return null;
nie zwracaj null - zwróć coś jak w linii 28

2020-08-24 19:30 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    return new ArrayList<>();
wcięcie?

2020-08-24 19:30 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    @GetMapping(value = "/getEmptyCart")
value miało być uwzględniane tylko w przypadku 2 metod HTTP tego samego typu w 1 kontrolerze. w przeciwnym przypadku mieliśmy się opierać na samych metodach HTTP

2020-08-24 19:30 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public CartDto addProductToCart(@RequestBody CartDto cartDto) {
według mnie sygnatura i typ zwracany póki co są ok, docelowo bym dodał identyfikator koszyka i ilość produktów do dodania.

2020-08-24 19:30 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +public class OrderDto {
order zostaw pusty..... kto inny go zaimplementuje

2020-08-24 19:39 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/CartController.java
>  package com.kodilla.ecommercee;
może stworzymy pakiet na kontrolery ? 
np. com.kodilla.ecommercee.controller?

2020-08-25 09:06 UTC, F1iper commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +public class OrderDto {
Wydaje mi się, że potrzebuję konstruktor do poprawnego przetestowania controllera w postmanie.

2020-08-25 18:08 UTC, hacker-msl approved these changes

2020-08-25 18:08 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +public class OrderDto {
konstruktor jest zawsze w klasie...

2020-08-25 18:09 UTC, merged