JDP200802-13
hacker-msl/project-jdp-2008-02 pull request #8
Opened 2020-08-24 14:32 UTC by hakhis

2020-08-24 19:35 UTC, hacker-msl requested changes
w zadaniu 13 jeszcze trzeba było zdefiniować repozytorium oraz zrobić relacje do innych encji, których nie mamy w projekcie. W takim wypadku musisz stworzyć puste klasy

2020-08-24 19:35 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @Column(name = "GROUP_ID")
adnotacja @Column nie jest potrzebna

2020-08-24 19:35 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @Column(name = "GROUP_NAME")
adnotacja @Column nie jest potrzebna

2020-08-24 19:35 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Group.java
> +    @Column(name = "PRODUCT_LIST")
adnotacja @Column nie jest potrzebna

2020-08-28 08:31 UTC, hacker-msl commented
mamy konflikty

2020-08-29 18:30 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +public class OrderController {
Zostały zmergowane z mastera

2020-08-29 18:30 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +public class UserController {
Zostały zmergowane z mastera

2020-08-29 18:32 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +//@Builder
To było dla poprzedniego commita, kiedy projekt mi się nie budował, w commicie JDP200802-13 v0.3 jest odkomentowane

2020-08-29 18:33 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/domain/ProductGroup.java
> +@Table(name = "PRODUCT_GROUPS")
To jest dla starego commita w commicie JDP200802-13 v0.3 klasa nazywa się Group.java i name jest wymagany

2020-08-29 18:34 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/repository/ProductGroupRepository.java
> +public interface ProductGroupRepository extends CrudRepository<ProductGroup, Long> {
To jest dla starego commita. W commicie JDP200802-13 v0.3 jest użyte JpaRepository, a klasa nazywa się GroupRepository.java

2020-08-29 18:45 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +@Table(name = "CARTS")
Poprawione w commicie JDP200802-13 v0.4

2020-08-29 18:45 UTC, hakhis commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Table(name = "PRODUCTS")
Poprawione w commicie JDP200802-13 v0.4

2020-08-30 17:07 UTC, hacker-msl approved these changes

2020-08-30 17:07 UTC, merged