Jdp200802 11
hacker-msl/project-jdp-2008-02 pull request #9
Opened 2020-08-28 18:59 UTC by F1iper

2020-08-28 19:15 UTC, hacker-msl requested changes

2020-08-28 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +@Table(name = "CARTS")
name nie jest potrzebne... adnotacja @Table też raczej nie

2020-08-28 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +@Table(name = "ORDERS")
tutaj to zostaw bo Order jest słowem kluczowym

2020-08-28 19:15 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Product.java
> +@Table(name = "PRODUCTS")
name nie jest potrzebne... adnotacja @table też raczej nie

2020-08-29 18:05 UTC, hacker-msl requested changes

2020-08-29 18:05 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +public class OrderController {
dalej widzę pusty kontroller

2020-08-29 18:05 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +public class UserController {
dalej widzę pusty kontroller

2020-08-29 18:24 UTC, AdamWojcicki1991 commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +public class UserController {
To zadanie dotyczy napisania Encji Order i ewentualnie rzeczy które są potrzebne do jej stworzenia i nic więcej. A co tu się dzieje to ja już nie ogarniam :P

2020-08-29 18:28 UTC, F1iper commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +public class OrderController {
Pusty OrderController po prostu przeniosłem do pakietu controller

2020-08-29 18:30 UTC, F1iper commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +public class UserController {
Cześc chłopaki, dokładnie to zadanie polegało na implementacji encji Order, przy okazji postanowiłem przenieść "puste" kontrolery do odpowiedniego pakietu
-UserController
-OrderController

2020-08-30 17:10 UTC, hacker-msl approved these changes

2020-08-30 17:11 UTC, hacker-msl requested changes
dałem approve ale musisz rozwiązać konflikty

2020-08-31 05:36 UTC, AdamWojcicki1991 commented
A i jeszcze jedna rzecz w zadaniu ze stworzeniem Encji trzeba również stworzyć do niej repozytorium którego jeszcze nie dodałeś :)

2020-09-01 09:46 UTC, hacker-msl commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
relacje skąd dokąd? zamiast skąd dokąd? jak mam się wypowiedzieć to daj mi małpkę z przodu :P o tak @AdamWojcicki1991

2020-09-02 16:02 UTC, AdamWojcicki1991 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private List<Product> products;
@hacker-msl Filip przygotowuje encję Order powyżej wkleiłem poglądowy model relacji w bazie danych. Zerknij proszę w wolnej chwili i powiedz co o tym sądzisz.

2020-09-02 16:02 UTC, AdamWojcicki1991 commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
@hacker-msl  ok już się poprawiłem :)

2020-09-05 12:39 UTC, AdamWojcicki1991 commented
Poprawiamy relacje na relacje zgodne ze schematem ustalonym na spotkaniu:DAILY 04.09.2020
- wykonanie taska JDP200802-10 i taska JDP200802-27,
- na ten moment mam maksymalna ilość tasków in Review jak się zwolnią będę kontynuować prace nad kolejnymi taskami.

2020-09-05 12:40 UTC, AdamWojcicki1991 commented
![image](https://user-images.githubusercontent.com/60105724/92305223-a4a22500-ef85-11ea-8262-0184d1f0feca.png)
Popraw relacje zgodnie z UML omówionym na spotkaniu :)

2020-09-10 05:08 UTC, hacker-msl commented
mamy konflikty z :
src/test/java/com/kodilla/ecommercee/SpringBootJPAIntegrationTest.java

2020-09-12 19:37 UTC, hacker-msl approved these changes

2020-09-12 19:38 UTC, merged